### ISSUE TITLE
0s Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/runner/_work/aura-oneclick/aura-oneclick/.github/actions/setup_action'. Did you forget to run actions/checkout before running your local action?

### ISSUE THREAD

**Issue by eilonash92** [jenseng/dynamic-uses#9]
Getting this error on the latest step 
0s Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/runner/_work/aura-oneclick/aura-oneclick/.github/actions/setup_action'. Did you forget to run actions/checkout before running your local action?

![image](https://github.com/jenseng/dynamic-uses/assets/29045521/18acdc5a-1cb7-445a-81be-c22403bc07d9)

**Comment by jenseng** [comment]
Hi @eilonash92, I haven't run into this before. Would you mind sharing or linking to your workflow file?

**Comment by jenseng** [comment]
Closing due to lack of response, unable to repro
